version: '3'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 9001 --reload
    container_name: documaster
    restart: always
    volumes:
      - .:/documaster
    ports:
      - "9001:9001"